version: '2'
services:
  db:
    image: mysql:latest
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  test:
    image: python:latest
    depends_on:
      - db
    command: pytest

