version: '2'
services:
  app:
    build: .
    depends_on:
      - db
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: db
      MYSQL_PORT: 3306
    command: ["pytest"]

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: russian_nouns
    volumes:
      - ./data:/docker-entrypoint-initdb.d

  test:
    build: .
    depends_on:
      - db
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: db
      MYSQL_PORT: 3306
    command: ["pytest"]
