name: ling 508 project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    env:
      ORG: "uazhlt"
      IMAGE_NAME: "ling508-summer2024-project"
      TAG: "latest"
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: russian_nouns
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=10s --health-retries=10

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Wait for MySQL to be healthy
        run: |
          until docker ps --filter health=healthy | grep mysql; do
            echo "Waiting for MySQL to be healthy..."
            sleep 5
          done

      - name: Build the docker image
        run: |
          docker build . --file Dockerfile --tag ${ORG}/${IMAGE_NAME}:${TAG}
      - name: Run the tests
        run: |
          docker run -i ${ORG}/${IMAGE_NAME}:${TAG} python -m pytest tests