name: ling 508 project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Create Docker Compose file
        run: |
          cat <<EOF > docker-compose.yml
          version: '3.8'
          services:
            mysql:
              image: mysql:5.7
              environment:
                MYSQL_ROOT_PASSWORD: root
                MYSQL_DATABASE: russian_nouns
              ports:
                - "3306:3306"
              healthcheck:
                test: ["CMD", "mysqladmin", "ping", "-uroot", "-proot"]
                interval: 10s
                timeout: 10s
                retries: 10
              networks:
                - test_network

            app:
              build:
                context: .
                dockerfile: Dockerfile
              depends_on:
                mysql:
                  condition: service_healthy
              environment:
                MYSQL_HOST: mysql
                MYSQL_PORT: 3306
                MYSQL_USER: root
                MYSQL_PASSWORD: root
                MYSQL_DATABASE: russian_nouns
              command: ["python", "-m", "pytest", "tests"]
              networks:
                - test_network

          networks:
            test_network:
              driver: bridge
          EOF

      - name: Build and run containers
        run: |
          docker-compose up --build --abort-on-container-exit

      - name: Print MySQL logs if tests fail
        if: failure()
        run: |
          MYSQL_CONTAINER_ID=$(docker ps --filter "name=mysql" -q)
          docker logs $MYSQL_CONTAINER_ID
